# Generated by Django 4.1.3 on 2022-11-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Chips', 'Chips'), ('Cookies', 'Cookies'), ('Fruit', 'Fruit'), ('Veggies', 'Veggies')], default=('Chips', 'Chips'), max_length=20)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('store_name', models.CharField(max_length=50)),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.snack')),
            ],
        ),
    ]
