# Generated by Django 4.1.3 on 2022-11-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchases',
            new_name='Purchase',
        ),
    ]
