# Generated by Django 4.1.3 on 2022-11-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='dishes',
            field=models.ManyToManyField(to='main_app.dish'),
        ),
    ]
